"""Create student_extensions table

Revision ID: 013cca489fe0
Revises: 6bd616c6417c
Create Date: 2025-02-14 01:51:38.325693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013cca489fe0'
down_revision = '6bd616c6417c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_extensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('diet_preference', sa.String(length=100), nullable=True),
    sa.Column('exercise_preference', sa.String(length=100), nullable=True),
    sa.Column('health_education', sa.String(length=100), nullable=True),
    sa.Column('correction_method', sa.String(length=50), nullable=True),
    sa.Column('right_keratometry_K1', sa.Float(), nullable=True),
    sa.Column('left_keratometry_K1', sa.Float(), nullable=True),
    sa.Column('right_keratometry_K2', sa.Float(), nullable=True),
    sa.Column('left_keratometry_K2', sa.Float(), nullable=True),
    sa.Column('right_axial_length', sa.Float(), nullable=True),
    sa.Column('left_axial_length', sa.Float(), nullable=True),
    sa.Column('right_sphere', sa.Float(), nullable=True),
    sa.Column('right_cylinder', sa.Float(), nullable=True),
    sa.Column('right_axis', sa.Float(), nullable=True),
    sa.Column('left_sphere', sa.Float(), nullable=True),
    sa.Column('left_cylinder', sa.Float(), nullable=True),
    sa.Column('left_axis', sa.Float(), nullable=True),
    sa.Column('right_dilation_sphere', sa.Float(), nullable=True),
    sa.Column('right_dilation_cylinder', sa.Float(), nullable=True),
    sa.Column('right_dilation_axis', sa.Float(), nullable=True),
    sa.Column('left_dilation_sphere', sa.Float(), nullable=True),
    sa.Column('left_dilation_cylinder', sa.Float(), nullable=True),
    sa.Column('left_dilation_axis', sa.Float(), nullable=True),
    sa.Column('right_anterior_chamber', sa.Float(), nullable=True),
    sa.Column('left_anterior_chamber', sa.Float(), nullable=True),
    sa.Column('other_remarks', sa.String(length=200), nullable=True),
    sa.Column('eye_fatigue', sa.String(length=100), nullable=True),
    sa.Column('right_intervention_dilation_sphere', sa.Float(), nullable=True),
    sa.Column('right_intervention_dilation_cylinder', sa.Float(), nullable=True),
    sa.Column('right_intervention_dilation_axis', sa.Float(), nullable=True),
    sa.Column('left_intervention_dilation_sphere', sa.Float(), nullable=True),
    sa.Column('left_intervention_dilation_cylinder', sa.Float(), nullable=True),
    sa.Column('left_intervention_dilation_axis', sa.Float(), nullable=True),
    sa.Column('post_intervention_vision_level', sa.String(length=50), nullable=True),
    sa.Column('left_naked_vision_change', sa.Float(), nullable=True),
    sa.Column('right_naked_vision_change', sa.Float(), nullable=True),
    sa.Column('left_sphere_change', sa.Float(), nullable=True),
    sa.Column('right_sphere_change', sa.Float(), nullable=True),
    sa.Column('left_cylinder_change', sa.Float(), nullable=True),
    sa.Column('right_cylinder_change', sa.Float(), nullable=True),
    sa.Column('left_intervention_effect', sa.String(length=50), nullable=True),
    sa.Column('right_intervention_effect', sa.String(length=50), nullable=True),
    sa.Column('left_sphere_intervention_effect', sa.String(length=50), nullable=True),
    sa.Column('right_sphere_intervention_effect', sa.String(length=50), nullable=True),
    sa.Column('left_cylinder_intervention_effect', sa.String(length=50), nullable=True),
    sa.Column('right_cylinder_intervention_effect', sa.String(length=50), nullable=True),
    sa.Column('intervention1', sa.DateTime(), nullable=True),
    sa.Column('intervention2', sa.DateTime(), nullable=True),
    sa.Column('intervention3', sa.DateTime(), nullable=True),
    sa.Column('intervention4', sa.DateTime(), nullable=True),
    sa.Column('intervention5', sa.DateTime(), nullable=True),
    sa.Column('intervention6', sa.DateTime(), nullable=True),
    sa.Column('intervention7', sa.DateTime(), nullable=True),
    sa.Column('intervention8', sa.DateTime(), nullable=True),
    sa.Column('intervention9', sa.DateTime(), nullable=True),
    sa.Column('intervention10', sa.DateTime(), nullable=True),
    sa.Column('intervention11', sa.DateTime(), nullable=True),
    sa.Column('intervention12', sa.DateTime(), nullable=True),
    sa.Column('intervention13', sa.DateTime(), nullable=True),
    sa.Column('intervention14', sa.DateTime(), nullable=True),
    sa.Column('intervention15', sa.DateTime(), nullable=True),
    sa.Column('intervention16', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_extensions')
    # ### end Alembic commands ###
