"""Add extra fields to Student model

Revision ID: 6bd616c6417c
Revises: ff6682b2db83
Create Date: 2025-02-13 14:27:54.546115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bd616c6417c'
down_revision = 'ff6682b2db83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('students', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('id_card', sa.String(length=18), nullable=True))
    op.add_column('students', sa.Column('phone', sa.String(length=15), nullable=True))
    op.add_column('students', sa.Column('parent_name', sa.String(length=50), nullable=True))
    op.add_column('students', sa.Column('parent_phone', sa.String(length=15), nullable=True))
    op.add_column('students', sa.Column('grade', sa.String(length=10), nullable=True))
    op.add_column('students', sa.Column('class_name', sa.String(length=10), nullable=True))
    op.add_column('students', sa.Column('vision_left_corrected', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('vision_right_corrected', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'vision_right_corrected')
    op.drop_column('students', 'vision_left_corrected')
    op.drop_column('students', 'class_name')
    op.drop_column('students', 'grade')
    op.drop_column('students', 'parent_phone')
    op.drop_column('students', 'parent_name')
    op.drop_column('students', 'phone')
    op.drop_column('students', 'id_card')
    op.drop_column('students', 'birthday')
    op.drop_column('students', 'age')
    op.drop_column('students', 'gender')
    # ### end Alembic commands ###
